#!/bin/bash
# Script for updating all git repos in subdirs.

BASEDIR=$(dirname "`[[ $0 == /* ]] && echo "$0" || echo "${PWD}/${0#./}"`")
### Define text styles  #######################################################
TXT_C="tput setaf"    # set text color in BGR format
TXT_R="tput sgr0"     # reset text format
TXT_B="tput bold"     # set bold
TXT_U="tput sgr 0 1"  # set underlined
###############################################################################

for DIR in $(find $BASEDIR -mindepth 1 -maxdepth 1 -type d) ; do
	cd $DIR 
	if [ -d "$DIR/.git" ]; then
		echo -e "`$TXT_C 2`Pulling $DIR`$TXT_R`"
		git pull
	fi
done
